title: Zainab Agha
email: zainabagha@sfsu.edu
description: Assistant Professor, HCI | Social Computing | Online Safety | UX Research
baseurl: ''
url: https://zainabagha.github.io
scholar_userid: TV1xodIAAAAJ
twitter_username: ''
github_username: zainabagha
minimal_mistakes_skin: default
markdown: kramdown
