title: Zainab Agha
email: zainabagha@sfsu.edu
description: 'Assistant Professor at San Francisco State University. Research: HCI,
  Online Safety, Social Computing, UX.'
baseurl: ''
url: https://zainabagha.github.io
scholar_userid: TV1xodIAAAAJ
minimal_mistakes_skin: default
markdown: kramdown

collections:
  pages:
    output: true
    permalink: /:name/
  publications:
    output: true
    permalink: /publication/:name/
